### ISSUE TITLE
gg returns sigsegv error

### ISSUE THREAD

**Issue by beet461** [vlang/v#10114]
I tried to run this with `v run test.v`:
```
import gg
import gx

struct App {
mut:
        gg &gg.Context
}

fn main() {
        mut app := &App{
                gg: 0
        }

        app.gg = gg.new_context(
                bg_color: gx.rgb(56, 69, 12)
        )

        app.gg.run()

}
```

I expected it to draw a blank window with no errors (maybe warnings), but I got this:
```
test: ../nptl/pthread_mutex_lock.c:424: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
7fdadeb64ef5 : at ???: RUNTIME ERROR: abort() called
4173257325203a75 : by ???
004c06f6 : at ???: RUNTIME ERROR: invalid memory access
004c0079 : by ???
004c0343 : by ???
004c04f7 : by ???
7fdadeb64f80 : by ???
4173257325203a75 : by ???
Terminated by signal 139 (SIGSEGV)
```

It worked before I did `v up`, but after I did it, it doesn't work. Same in Windows 10

OS: Arch Linux
Arch: x86

**Comment by kahsa** [comment]
`v/examples/gg/rectangles.v` doesn't work also on ArchLinux.

**Comment by JalonSolov** [comment]
Same failure on Ubuntu 21.04.

**Comment by penguindark** [comment]
On windows the `examples\sokol\01_cubes` run normally.
It use gg and the app of gg.

**Comment by beet461** [comment]
> Same failure on Ubuntu 21.04. `V 0.2.2 7a4ec9f`
> 
> ```
> jalon@Ripper:~/git/v$ v run examples/gg/rectangles.v
> /home/jalon/git/v/thirdparty/stb_image/stbi.o not found, building it in /home/jalon/.vmodules/cache/43/43065c77ddb3e098a834c47038f75952.o ...
> rectangles: ../nptl/pthread_mutex_lock.c:424: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
> 7f85083d3fbb : at ???: RUNTIME ERROR: abort() called
> 4173257325203a75 : by ???
> 004c0a46 : at ???: RUNTIME ERROR: invalid memory access
> 004c03c9 : by ???
> 004c0693 : by ???
> 004c0847 : by ???
> 7f85083d4040 : by ???
> 4173257325203a75 : by ???
> Segmentation fault
> jalon@Ripper:~/git/v$
> ```

I fixed the stbi image error by copying the header file from `v/thirdparty/stb_image/stb_image.h` to the directory of my v file. But I do not know about the rest

**Comment by beet461** [comment]
Note: I have tried re installing v by cloning the repo and compiling it with make. No errors

**Comment by JalonSolov** [comment]
I wipe out the cache, deleted the local clone, cloned fresh from github, rebuilt with make, and tried again.

Still get the failure on Ubuntu 21.04.

**Comment by spytheman** [comment]
The minimal gg program (using sokol) is:
```v
import gg
import gx

struct App {
mut:
        gg &gg.Context
}

fn main() {
        mut app := &App{
                gg: 0
        }
        app.gg = gg.new_context(
                bg_color: gx.rgb(56, 69, 12)
                frame_fn: frame_fn
                user_data: app
        )
        app.gg.run()
}

fn frame_fn(app &App) {
        app.gg.begin()
        app.gg.end()
}
```

**Comment by spytheman** [comment]
Note that you need both:
```v
   frame_fn: frame_fn
   user_data: app
```
otherwise, you can not access gg methods in the frame function, and so you can not call:
```v
    app.gg.begin()
    app.gg.end()
```
which are needed.

**Comment by spytheman** [comment]
If you do not need to pass state from frame to frame, this will also work:

```v
import gg
import gx

const gg_context = gg.new_context(
        bg_color: gx.rgb(56, 69, 12)
        frame_fn: frame_fn
)

fn frame_fn(x voidptr) {
        gg_context.begin()
        gg_context.end()
}

fn main() {
        gg_context.run()
}
```

**Comment by spytheman** [comment]
> > rectangles: ../nptl/pthread_mutex_lock.c:424: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
> > 7f85083d3fbb : at ???: RUNTIME ERROR: abort() called

The failing assert should be fixed in d5c306c .

**Comment by JalonSolov** [comment]
Fixes it for me.

**Comment by spytheman** [comment]
@beet461 does the examples work for you too after `v up`?

**Comment by kahsa** [comment]
His code works for me on ArchLinux.

**Comment by beet461** [comment]
OK, it worked after I did `v up` once again, but I have no idea what caused the issue in the first place.
But, when I followed spytheman's example (before `v up`) it doesn't work.

**Comment by medvednikov** [comment]
@beet461 as you can see from the commit, it was due to a missing ` -lpthread`
