### ISSUE TITLE
c output doesn’t compile on freebsd

### ISSUE THREAD

**Issue by bakul** [vlang/v#12100]
**V version:** latest
**OS:** freebsd

**What did you do?**
v -o hello.c hello.v
cc hello.c

where hello.v is `fn main() { println("hello") }`. Note that compiling it with just v works fine. And compiling to c on linux (ubuntu) and compiling the c output with a c compiler works fine.

**What did you expect to see?**
A clean compile.
 
**What did you see instead?**
The following output is from clang. gcc fails for the same reason but with a slightly different error output.
```
hello.c:10352:2: warning: implicit declaration of function 'signal' is invalid in C99 [-Wimplicit-function-declaration]
        signal(11, v_segmentation_fault_handler);
        ^
1 warning generated.
ld: error: undefined symbol: backtrace
>>> referenced by hello.c
>>>               /tmp/hello-2dcca1.o:(print_backtrace_skipping_top_frames_bsd)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by hello.c
>>>               /tmp/hello-2dcca1.o:(print_backtrace_skipping_top_frames_bsd)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bakul** [comment]
Suggest updating documentation to include `-lexecinfo` for FreeBSD (and may be other BSDs too). 

The signal warning can be removed by adding `#include <signal.h>` in generated C code.

**Comment by medvednikov** [comment]
Fixed and added to CI.

**Comment by bakul** [comment]
Thanks. Though it still doesn't work (the exact same 3 lines work fine on ubuntu).
```
$ echo 'fn main() { println("Hello") } > hello.v
$ v -o hello.c hello.v
$ cc -Ithirdparty/libgc/include hello.c thirdparty/libgc/gc.c
hello.c:2097:4: warning: expression result unused [-Wunused-value]
  (*(int*)_t1.data);
   ^~~~~~~~~~~~~~~
hello.c:12070:2: warning: implicit declaration of function 'signal' is invalid in C99 [-Wimplicit-function-declaration]
        signal(11, v_segmentation_fault_handler);
        ^
2 warnings generated.
ld: error: undefined symbol: backtrace
>>> referenced by hello.c
>>>               /tmp/hello-c9fe04.o:(print_backtrace_skipping_top_frames_bsd)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by hello.c
>>>               /tmp/hello-c9fe04.o:(print_backtrace_skipping_top_frames_bsd)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by spytheman** [comment]
> Suggest updating documentation to include -lexecinfo for FreeBSD (and may be other BSDs too).

What documentation do you mean more precisely: README.md, doc/docs.md or something else?

That flag is supplied automatically by V itself on FreeBSD and NetBSD now, so most users should not need to care about it, and the ones that do, can use -showcc to see what flags are passed/needed by V itself.

**Comment by bakul** [comment]
Probably there should be a section for *platform specific* issues, with subsection for  platforms that require some special handling. Either in doc/docs.md or a separate doc/platform-dependent.md or something.

**Comment by spytheman** [comment]
I agree in general, but in this specific instance, V itself adds the flag normally. 

Compiling the produced C code manually is not the general case, and most users on FreeBSD etc can just do `make` to build V itself, and `v hello.v` for building V programs, not `v -o hello.c hello.v`, then invoking cc themselves.

**Comment by bakul** [comment]
That may be fine if your main() is in V but if you want to write a library in V for use with C programs these things may matter. Though I haven't done this yet so this is just a theoretical complaint!
