### ISSUE TITLE
circular import causes weird V panic

### ISSUE THREAD

**Issue by d2verb** [vlang/v#1214]
**V version:** 0.1.15
**OS:** Xubuntu 18.04 LTS

**What did you do?**
make following project and execute `v main.v`
```
~/W/t/cir ❯❯❯ ls
mod1  mod2  main.v
~/W/t/cir ❯❯❯ cat main.v
module main

import mod1

fn main() {
	_ := mod1.Mod1Const
}
~/W/t/cir ❯❯❯ cat mod1/mod1.v                                                                                                                                                            
module mod1

import mod2

const (
	Mod1Const = mod2.Mod2Const
)
~/W/t/cir ❯❯❯ cat mod2/mod2.v
module mod2

import mod1

const (
	Mod2Const = mod1.Mod1Const
)
```

**What did you expect to see?**
compile error showing circular import exists
 
**What did you see instead?**
```
.main.c: In function ‘main’:
.main.c:3107:6: error: variable or field ‘_’ declared void
 void _= mod1__Mod1Const ;
      ^
.main.c:3107:9: error: void value not ignored as it ought to be
 void _= mod1__Mod1Const ;
         ^~~~~~~~~~~~~~~
.main.c: In function ‘init_consts’:
.main.c:3111:63: error: ‘mod1__Mod1Const’ has an incomplete type ‘void’
  void init_consts() { g_str_buf=malloc(1000); mod1__Mod1Const =  mod2__Mod2Const;
                                                               ^
.main.c:3112:17: error: ‘mod2__Mod2Const’ has an incomplete type ‘void’
 mod2__Mod2Const =  mod1__Mod1Const; }
                 ^
V panic: clang error
```

**Comment by joe-conigliaro** [comment]
@d2verb it's known issue, it's being worked on

**Comment by joe-conigliaro** [comment]
@d2verb Can you please try this again, still no circular import detection, but this error should be fixed

**Comment by joe-conigliaro** [comment]
@d2verb This should fix it: https://github.com/vlang/v/pull/1237

**Comment by d2verb** [comment]
@joe-conigliaro circular import detected!
```
>> v ./main.v 
V panic: Circular import detected between modules: mod1 & mod2.
```
nice work!

**Comment by d2verb** [comment]
@joe-conigliaro 
If dependency looks like
```
mod1 -> mod2 -> mod3
 ^               |
 |_______________|
```
the error still occured...
```
.main.c: In function ‘init_consts’:
.main.c:3352:63: error: ‘mod1__Mod1Const’ has an incomplete type ‘void’
  void init_consts() { g_str_buf=malloc(1000); mod1__Mod1Const =  mod2__Mod2Const;
                                                               ^
.main.c:3353:17: error: ‘mod3__Mod3Const’ has an incomplete type ‘void’
 mod3__Mod3Const =  mod1__Mod1Const;
                 ^
.main.c:3354:17: error: ‘mod2__Mod2Const’ has an incomplete type ‘void’
 mod2__Mod2Const =  mod3__Mod3Const; }
                 ^
V panic: clang error
```

**Comment by joe-conigliaro** [comment]
@d2verb  thanks i will look into it

**Comment by joe-conigliaro** [comment]
@d2verb I will have this fixed soon

**Comment by joe-conigliaro** [comment]
I have fixed the issue but I need to detect if a const or struct references a circular import module, and only panic then. because that the only time it will cause problems. Otherwise I think they should be allowed. What do you think?

**Comment by d2verb** [comment]
@joe-conigliaro I'm with you. circular import doesn't mean circular dependency. 
If there is not circular dependency, I think we can allow circular import.

**Comment by joe-conigliaro** [comment]
@d2verb I talked to Alex and for now there will be no circular importing allowed at all, like in go.
This has been fixed!

**Comment by d2verb** [comment]
@joe-conigliaro Amazing works! thanks!

**Comment by joe-conigliaro** [comment]
@d2verb thanks for reporting!
