### ISSUE TITLE
socket client read does not return all data once above certain size, tried bufferend and unbuffered

### ISSUE THREAD

**Issue by despiegk** [vlang/v#13447]
redisclient as implemented in crystallib does not seem to get all data back from redis server
it cuts off the data, tried lots of different combinations but couldn't get there

I think the issue has nothing to do with redis server, it something with the sockets I think

## reproduce

```bash
v install despiegk.crystallib
cd ~/.vmodules/despiegk/crystallib/redisclient
#go to branch development_a5
git checkout development_a5
v test ~/.vmodules/despiegk/crystallib/redisclient
```

## in doc found following

![image](https://user-images.githubusercontent.com/6021844/153700566-32b92f77-e4c6-4eaf-aa63-8289fa3e4000.png)

but ```io.new_buffered_reader({reader: io.make_reader(con)})``` is no longer supported I think, at least couldn't find

## code

see crystallib/redisclient/redisclient.v

another way to test

```
 v run ~/.vmodules/despiegk/crystallib/redisclient/examples/redis_basic_example.v
```

super strange behaviour
```
DATA SEND TO REDIS & RECEIVED IS NOT SAME (test 0
SIZE DATA SEND: 100000
SIZE DATA RECEIVED: 100000
100000
48936
```
size data size is same, but count of the a's is different?

**Comment by despiegk** [comment]
see also ...despiegk/crystallib/redisclient/examples/redis_connect.v

```
module main
import despiegk.crystallib.redisclient
import time

fn conn(c int){
	mut redis := redisclient.get_local_new()  or { panic(err.str()+"\n"+c.str())}
	redis.set('test', 'some data')   or { panic("set"+err.str()+"\n"+c.str())}
	redis.get('test')  or{ panic("get"+err.str()+"\n"+c.str())}
}

fn redistest() ? {

	mut threads := []thread{}

	for c in 0..10000{
		//even if going slower does not work?
		time.sleep(100*time.millisecond)
		println(c)
		threads << go conn(c)
	}
	threads.wait()

	println("TEST OK")

}

fn main() {
	redistest() or { panic(err) }
}

```

error

```
0
1
2
3
4
5
V panic: dial_tcp failed for address 127.0.0.1:6379
5
v hash: a21f456
0   redis_connect                       0x0000000100a68890 main__conn + 212
1   redis_connect                       0x0000000100a687a4 main__conn_thread_wrapper + 32
2   libsystem_pthread.dylib             0x000000018e379240 _pthread_start + 148
3   libsystem_pthread.dylib             0x000000018e374024 thread_start + 8
```

**Comment by vincenzopalazzo** [comment]
Mh, I need to reproduce it with a simple env, there are too much stuff involved in your example.

Can you help me to reproduce the problem with a minimal reproducible example?

**Comment by despiegk** [comment]
probaby vlang install does not clone all branches
https://github.com/freeflowuniverse/crystallib/tree/development_a5
branch exists though
will try to make it easier to test

**Comment by despiegk** [comment]
just managed to reproduce on osx arm

```
/Users/despiegk/.vmodules/despiegk/crystallib/redisclient/redisclient.v:9:8: warning: module 'io' is imported but never used
    7 | import time
    8 | import resp2
    9 | import io
      |        ~~
   10 |
   11 | const default_read_timeout = net.infinite_timeout
0
1
2
3
V panic: dial_tcp failed for address localhost:6379
```

**Comment by spytheman** [comment]
I've just pushed a 2 part fix:
1. for V's `net` module for TcpConn.read_line in 74048e2.
2. for the `despiegk.crystallib` module (in a development_a6 branch, it is based on development_a5, but has 2 additional commits).

With this 2 fixes, and when using Redis 6.2:
![image](https://user-images.githubusercontent.com/26967/153775567-7b939e7f-a121-4d0f-9c86-d7c5d5658ebd.png)

With Redis 5.0.7 (the default in Ubuntu 20.04), most of the tests pass, except one:
```
/home/delian/.vmodules/despiegk/crystallib/redisclient/redisclient_test.v:118: ✗ fn test_set_opts
   > assert redis.set_opts('test8', '012', despiegk.crystallib.redisclient.SetOpts{....}) == true
     Left value: false
    Right value: true
```

I've tried also the additional programs here, they all work with Redis 6.2 (the latest stable release from https://redis.io/download).

**Comment by spytheman** [comment]
@despiegk please check if everything is ok?

**Comment by despiegk** [comment]
thank you the bigger data test works now, fantastic.

the redis connect example still fails, could be has to do with M1 ARM platform (OSX)

```
cd /tmp
git clone git@github.com:freeflowuniverse/crystallib.git
cd crystallib
git checkout development_a5
git pull
v run redisclient/examples/redis_connect.v
```

```bash
despiegk@kristofgouna crystallib % v run /Users/despiegk/despiegk/crystallib/redisclient/examples/redis_connect.v
0
1
2
3
V panic: dial_tcp failed for address localhost:6379
3
v hash: ae0e90f
0   redis_connect                       0x0000000102ea41d4 main__conn + 212
1   redis_connect                       0x0000000102ee7b14 main__redistest_nothreads + 96
2   redis_connect                       0x0000000102ee7b7c main__main + 20
3   redis_connect                       0x0000000102ee8a20 main + 48
4   dyld                                0x000000010315d0f4 start + 520
```

**Comment by despiegk** [comment]
will make new examples
