### ISSUE TITLE
Wrong assumption in for loop that use `in` operator

### ISSUE THREAD

**Issue by dedesite** [vlang/v#14440]
**V version:** V 0.2.4 65d9c8f
**OS:** Ubuntu 20.04

**What did you do?**
I tried to use a for loop as a `while` with a `in` operator use for condition : 
```v
type TokenValue = rune | u64

fn main() {
	val := `+`
	for val in [TokenValue(`+`), TokenValue(`-`)] {
		println("ok")
		break
	}
}
```

**What did you expect to see?**
The program to run flawlessly and print "ok"
 
**What did you see instead?**
```
5:10: error: redefinition of value iteration variable `val`
```
The compile assume that I want to do a `for..in` loop but it's not the case.

**Comment by JalonSolov** [comment]
Whatever you meant, you literally wrote
```v
for val in
```
Which is a `for..in` loop.

The real question is:  Why did V think you were redefining val?

**Comment by KamkoAmoh** [comment]
The code is not right.

1. you declared `val :=  '+'`
2. than you use `val` as a placeholder name in a for loop
3. you break after one iteration

I did test the behavior, don't see any issue if the code is written correctly;

**Comment by KamkoAmoh** [comment]
@dedesite maybe you meant this issue?
https://github.com/vlang/v/issues/14439

**Comment by dedesite** [comment]
Sorry, but I don't understand your remarks.
Is `val in [TokenValue(`+`), TokenValue(`-`)]` a valid boolean condition ?
If so, it can be use as a condition for a `for` loop which act like a `while`, not a `for .. in`

I know, the synax is the same as a `for .. in` but it is not a `for .. in`. The compiler should understand regarding the context what I want to do.

If it's not possible, then there is a problem in the `for` loop syntax for me.

**Comment by depperm** [comment]
So the [docs](https://github.com/vlang/v/blob/master/doc/docs.md#in-operator) say it should be a valid operation, at least to me. Seems like a bug

**Comment by JalonSolov** [comment]
Do `v up` and try it now.  Should be fixed by #14448

**Comment by depperm** [comment]
The original issue persists but no longer does `if` one cause an error

**Comment by medvednikov** [comment]
> The real question is: Why did V think you were redefining val?

Because that's what's literally happening. The compiler's behavior is correct.

**Comment by dedesite** [comment]
Thanks again @yuyi98 for this quick fix !
That's kind of awesome to see almost "in live" the compiler get fixed.

**Comment by spytheman** [comment]
the syntax ambiguity can be resolved with `for (val in [TokenValue(`+`), TokenValue(`-`)]) {`

**Comment by dedesite** [comment]
Ok thanks @spytheman, out of curiosity why the previous commit was not good ?
It worked well for me without the need of parenthesis.

**Comment by spytheman** [comment]
@dedesite - see the comments in https://github.com/vlang/v/pull/14451

without the (), it works, but it is ambiguous for the readers - see how @medvednikov perceived it to be as `for x in array {` (i.e. loop over array, assigning each element to x).

**Comment by spytheman** [comment]
@dedesite there is now also a new PR - https://github.com/vlang/v/pull/14459 , that @yuyi98 made, that will make the error message clearer.

**Comment by dedesite** [comment]
@spytheman I don't see how the `()` are less ambiguous.
`val in [TokenValue(`+`), TokenValue(`-`)]` can be either a boolean expression or a "iterator" declaration and adding parenthesis doesn't change this fact no ?
