### ISSUE TITLE
Hot code reloading doesn't work on windows

### ISSUE THREAD

**Issue by DJ-Dav** [vlang/v#17612]
### Describe the bug

running `v -live bounce.v`
throws the following error:
new_lib_path: [me]\\.cache/tmp.1.main.dll does not exist
errors while compiling main.v

### Expected Behavior

The code compiles and runs, and changes when bounce.v is edited

### Current Behavior

the error message:
new_lib_path: C:\\Users\\davyj\\.cache/tmp.1.main.dll does not exist
errors while compiling main.v

### Reproduction Steps

copy bounce.v on windows, and run v -live bounce.v

### Possible Solution

the folder does contain tmp.1.bouce.exe so this may be as simple as fixing one string in one line of code

### V version

Current V version: V 0.3.3 3197ec1

### Environment details (OS name and version, etc.)

OS: windows, Microsoft Windows 11 Home v22621 64-bit
Processor: 4 cpus, 64bit, little endian,
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version

getwd: C:\Users\davyj
vmodules: C:\Users\davyj\.vmodules
vroot: C:\Users\davyj\v
vexe: C:\Users\davyj\v\v.exe
vexe mtime: 2023-03-12 14:29:08
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 d7a418f.3197ec1

Git version: git version 2.39.2.windows.1
Git vroot status: weekly.2023.10-40-g3197ec1a
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 1e6e7c6f

**Comment by DJ-Dav** [comment]
This bug is because it wants tmp.1.bounce.dll, but it is actually a .exe
This could probably be fixed with 1 line of code, if someone can find it I will fix it and create the pull request.

**Comment by keenfoong** [comment]
Just adding my 2c, this is also happening on my windows system:

```
D:\programs\v>v -cg -live run examples/hot_reload/message.v
Unhandled Exception 0xC0000005
C:/Users/distantf/AppData/Local/Temp/v_0/message.16682603741558348194.tmp.c:8385: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/distantf/AppData/Local/Temp/v_0/message.16682603741558348194.tmp.c:8352: by print_backtrace_skipping_top_frames
C:/Users/distantf/AppData/Local/Temp/v_0/message.16682603741558348194.tmp.c:9162: by unhandled_exception_handler     
7ffc3e288b1c : by ???
RUNTIME ERROR: invalid memory access

D:\programs\v>v -live run examples/hot_reload/message.v     
Unhandled Exception 0xC0000005
C:/Users/distantf/AppData/Local/Temp/v_0/message.5612342507701216301.tmp.c:8383: at print_backtrace_skipping_top_frames_tcc: Backtrace
C:/Users/distantf/AppData/Local/Temp/v_0/message.5612342507701216301.tmp.c:8350: by print_backtrace_skipping_top_frames
C:/Users/distantf/AppData/Local/Temp/v_0/message.5612342507701216301.tmp.c:9160: by unhandled_exception_handler
7ffc3e288b1c : by ???
RUNTIME ERROR: invalid memory access
```

V Version: V 0.4.3 30d6f7b

System information
```
         Operating System: Windows 10 Home 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: X570 AORUS PRO WIFI
                     BIOS: F6b (type: UEFI)
                Processor: AMD Ryzen 9 3900X 12-Core Processor             (24 CPUs), ~3.8GHz
                   Memory: 65482MB RAM
      Available OS Memory: 65482MB RAM
                Page File: 30631MB used, 38867MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Not Supported

```

**Comment by andorxornot** [comment]
has a hot reboot for windows ever worked? i check v every six months and seems there was a working version only about two years ago then something broke and it's still not working.

**Comment by medvednikov** [comment]
Works now.
