### ISSUE TITLE
for/in cannot iterate over C structs

### ISSUE THREAD

**Issue by spiveeworks** [vlang/v#21047]
### Describe the bug

When defining a `next` method for a C struct, for/in loops don't generate valid C code.

### Reproduction Steps

struct C.MyCStruct {
    x int
}

fn (mut self C.MyCStruct)next() ?int {
    return self.x
}

fn main() {
    iter := C.MyCStruct{}
    for each in iter {
    }
}

### Expected Behavior

This should produce C code that calls C__MyCStruct_next in a loop.

### Current Behavior

The following code is generated:

	MyCStruct iter = ((MyCStruct){.x = 0,});
	MyCStruct _t1 = iter;
	while (1) {
		_option_int _t2 = struct MyCStruct_next(&_t1);
		if (_t2.state != 0) break;
		int each = *(int*)_t2.data;
	}

The problem with this code is it tries to call `struct MyCStruct_next` as a function, instead of `C__MyCStruct_next`.

Adding a `@[typedef]` attribute unsurprisingly drops the `struct` part, just giving `MyCStruct_next` without the `C__` namespace.

### Possible Solution

It seems like the code that generates for loops, that tries to generate the function name `Module__Typename_next`, is calling something that emits the C type directly, instead of something that emits the actual namespace associated with the type.

### Additional Information/Context

Similar to another bug I just reported, this came up while trying to add iterator implementations to a type, but this time when I tried to iterate over the type itself, rather than a wrapper. (I had two different types, one of them suited being wrapped where the other one suited being iterated over directly.)

### V version

V 0.4.4 549654a

### Environment details (OS name and version, etc.)

V full version: V 0.4.4 386bd77.549654a
OS: windows, Microsoft Windows 10 Pro v19045 64-bit
Processor: 4 cpus, 64bit, little endian,

getwd: C:\Users\Owner
vexe: C:\Program Files\v\v.exe
vexe mtime: 2024-03-17 05:49:07

vroot: contains spaces, value: C:\Program Files\v
VMODULES: OK, value: C:\Users\Owner\.vmodules
VTMP: OK, value: C:\Users\Owner\AppData\Local\Temp\v_0

Git version: git version 2.37.2.windows.2
Git vroot status: weekly.2024.11-39-g549654ae
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc: N/A
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

**Comment by Delta456** [comment]
I believe iteration over C structs must have a `typedef` attribute for them to work.

**Comment by spytheman** [comment]
No, only the presence of next() ?Type method should matter. It is a pure cgen bug (perhaps no one has tried to use an iterator over a C struct, and bothered to report it), and should be fixed there.

**Comment by spiveeworks** [comment]
> I believe iteration over C structs must have a `typedef` attribute for them to work.

When you add the typedef attribute it creates C code that parses, `MyCStruct_next(...)` instead of `struct MyCStruct_next(...)`, but it still doesn't compile, because `MyCStruct_next` isn't a real function. With or without the `typedef` attribute it should be generating `C__MyCStruct_next` as the function name, which as mentioned is purely a codegen bug.

**Comment by spiveeworks** [comment]
Trying to learn a bit about the codebase by seeing if I can find this bug in the code.

https://github.com/vlang/v/blob/d783cda67187df23d3458a7a884bb56670ad2556/vlib/v/gen/c/for.v#L438
```
		receiver_styp := g.typ(receiver_typ)
```
This sets receiver_styp to `struct MyCStruct*` or `MyCStruct*`

we want to change this to something like `g.cc_type(receiver_typ, false)`

**Comment by spiveeworks** [comment]
I have made a fork with this change, but I don't know enough about compiler development to test it manually, let alone to add an automated test for it.
https://github.com/spiveeworks/v/commit/e20c56078d0f59a0024f2a8d3e4bf589a407323a

**Comment by felipensp** [comment]
> I have made a fork with this change, but I don't know enough about compiler development to test it manually, let alone to add an automated test for it. [spiveeworks@e20c560](https://github.com/spiveeworks/v/commit/e20c56078d0f59a0024f2a8d3e4bf589a407323a)

Please, submit a pull request.

**Comment by spytheman** [comment]
Fixed by #21052 .
