### ISSUE TITLE
Error while compiling with -x64 flag: array_bare.v:20: bad ret type

### ISSUE THREAD

**Issue by ghost** [vlang/v#3294]
**V version:** V 0.1.24 807c16d
**OS:** Debian GNU/Linux bullseye/sid

**What did you do?**
v -x64 main.v

**What did you expect to see?**
Hello, World!
 
**What did you see instead?**
RET Typ array
RET Typ array
/home/nick/.vlang/vlib/builtin/bare/array_bare.v:20: bad ret type

**Comment by medvednikov** [comment]
Fixed.

**Comment by ntilotta** [comment]
@medvednikov unfortunately it appears not fixed yet.

```v
fn main() {
	name := 'Bob'
	println('$name')
}
```

it works with _v build -prod main.v_, but with _v -x64 main.v_ I got this error instead:

_parse file "main.v"
x.v:3: unknown function `println`
main.v:3: syntax error: unexpected `$2`, expecting `,`_

**Comment by medvednikov** [comment]
hello world works with -x64 now, not string interpolation, but it's a different issue
