### ISSUE TITLE
Error when running Vweb project from Vweb tutorial. 

### ISSUE THREAD

**Issue by MintCollie** [vlang/v#3426]
**V version:** 
V 0.1.24 4c55d36
**OS:** 
Arch linux 5.4.11-arch1-1
**What did you do?**
followed along with the "Building a 150 KB web blog in V with 0 dependencies" guide and received and error upon running.

**What did you expect to see?**
`Running a Vweb app on http://localhost:8080 ...`
 
**What did you see instead?**
`/home/mint/Projects/v/vlib/vweb/vweb.v:140:13: struct `App` is private`
`  138|  println('Running a Vweb app on http://localhost:$port ...')`
 ` 139|  l := net.listen(port) or { panic('failed to listen') }`
  `140|  mut app := T{}`
  `                            ^`
  `141|  app.vweb = Context{}`
  `142|  app.init()`
                           `

**Comment by noahsnowc** [comment]
Same issue
**V Version:**
V 0.1.24 502ee8a
**OS:**
Pop!_OS 19.10 

**What did you do?**
followed along with the "Building a 150 KB web blog in V with 0 dependencies" guide and received and error upon running.

**What did you expect to see?**
Running a Vweb app on http://localhost:8080 ...

**What did you see instead?**
```
../Languages/v/vlib/vweb/vweb.v:140:13: struct `App` is private
  138| 	println('Running a Vweb app on http://localhost:$port ...')
  139| 	l := net.listen(port) or { panic('failed to listen') }
  140| 	mut app := T{}
             	     ^
  141| 	app.vweb = Context{}
  142| 	app.init()
```

**Comment by medvednikov** [comment]
Fixed.

**Comment by wolfEXE57** [comment]
> Fixed.

Is this in a specific commit yet? I updated v and still received the same error.

**Comment by serkonda7** [comment]
The tutorial works fine with V 0.1.29 4774c89
