### ISSUE TITLE
can't invoke interface method

### ISSUE THREAD

**Issue by wilesun** [vlang/v#4577]
**V version:0.1.26** 
**OS:ubuntu** 

**What did you do?**
```v
import  eventbus

const (
	eb = eventbus.new()
	channel_over = 'chan.close'
)

pub interface Closable {
        close()
}

pub fn publish(sender voidptr, args voidptr) {
	eb.publish(channel_over, sender, args)
}

pub fn subscribe(receiver Closable) {
	eb.subscriber.subscribe_method(channel_over,  on_close, receiver)
}

fn on_close(receiver voidptr, args voidptr, sender voidptr) {
	w := Closable(receiver)
	w.close()
}
```
compile:
error: unknown method close

**What did you expect to see?**

 
**What did you see instead?**

**Comment by nedpals** [comment]
@wilesun Interface has been fixed in the new build. Can you try updating the compiler and rerun the code?

**Comment by wilesun** [comment]
thanks,the problem still exists。v has not chan(golang), I want to temporarily replace with eventbus,the Interface is must,but the only interface example is logger,I don't known  how to use Interface

**Comment by nedpals** [comment]
@wilesun 

1. You can see the examples in the docs: https://github.com/vlang/v/blob/master/doc/docs.md#interfaces
2. Or the Eventbus Docs: https://github.com/vlang/v/blob/master/vlib/eventbus/README.md
3. Or the Eventbus tests: https://github.com/vlang/v/blob/master/vlib/eventbus/eventbus_test.v

**Comment by wilesun** [comment]
The interface should be a pointer type. The interface in golang is also a pointer type. The interface in v seems to be a copy of the object. What should it be? Can you tell?

**Comment by wilesun** [comment]
why to use memdup??
`
return (ctx__Closable){
           ._object = (void*) memdup(&x, sizeof(web__Server)),
           ._interface_idx = _ctx__Closable_web__Server_index };
`

**Comment by ntrel** [comment]
First I added `module ev` to silence the `pub` errors.

Compiling now gives an error for this line:

> 	eb.subscriber.subscribe_method(channel_over,  on_close, receiver)

```
event.v:20:2: error: cannot modify constant `ev.eb`
```

`eb` is immutable, so `eb.subscriber` is immutable too. `subscribe_method` requires a mutable receiver, hence the error. It seems this issue is invalid.

**Comment by shadowninja55** [comment]
as ntrel said this example is trying to mutate a constant and use it as a global. interface methods work fine in normal code, so i'm closing this for now unless someone has an objection.
