### ISSUE TITLE
`match` should be type-safe

### ISSUE THREAD

**Issue by tim-st** [vlang/v#4711]
```v
fn main() {
	x := i8(1)
	match x {
		1.0 {
			println("got float 1.0")
		}
		0b1 {
			println("got byte 1")
		}
		true {
			println("got bool 1")
		}
		1 {
			println("got int 1")
		} else {
			println("got other value")
		}
	}
}
```

I think the match-branch should only allow the type of the variable to match.
Tested on `V 0.1.26 50a8373.c112b3a`(linux amd64)

**Comment by medvednikov** [comment]
Fixed:

```
error: cannot use `bool` as `i8` in `match`
```

**Comment by tim-st** [comment]
I think the problem remains for the other types. After removing the bool it runs again in the first branch (float). I think it would be best that all types in match should have type(x).

**Comment by medvednikov** [comment]
it uses the same rule for comparison

there's no need to cast number literals in V, like in Go

**Comment by tim-st** [comment]
If you allow for example 1.0 for type i8 then that would mean that the second part I wrote is true: the example code above has now undetected duplicate cases.

**Comment by medvednikov** [comment]
Yeah that needs to be detected:

```
a := 0
switch a {
case 0.0:
case 0:
}
./prog.go:12:6: duplicate case 0 in switch
```

**Comment by medvednikov** [comment]
That should be a separate issue. Detect duplicate const literals in `match`

**Comment by medvednikov** [comment]
https://github.com/vlang/v/issues/4712

**Comment by tim-st** [comment]
Ok, it seems to work good for more important types like `struct` and `void` (these are not autoconverted).
