### ISSUE TITLE
fmt: double & added

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#5118]
**V version:** 
0.1.27
```
// before fmt
module main
struct Foo {
	i int
}
struct Bar {
	f Foo = &Foo(0)
}

fn main() {}
```
```
//after fmt
module main
struct Foo {
	i int
}
struct Bar {
	f Foo = &&Foo(0) // error: expr(): bad token `&&` 
}

fn main() {}
```

**Comment by duarteroso** [comment]
Maybe related. A & is added to the input of the 'len' argument

```
// before
module main
struct Foo {
	i int
	a []int
}
struct Bar {
	f Foo = &Foo(0)
}
fn main() {
	size := 5
	f := &Foo{
		a: []int{len: int(size)}
	}
}
```

```
// after
module main
struct Foo {
	i int
	a []int
}
struct Bar {
	f Foo = &&Foo(0)
}
fn main() {
	size := 5
	f := &Foo{
		a: []int{len: &int(size)}
	}
}
```

**Comment by spytheman** [comment]
Your first example shoud be fixed in 077e06b .

**Comment by duarteroso** [comment]
Another case that is still happening after your changes.
Instead of a double ampersand being added in the struct definition, it is added to the instance creation.

```
struct Foo {}
struct Bar {
	f &Foo = &Foo(0)
}
fn main() {
	b := &Bar{
		f: &Foo(1)
	}
}
```
```
struct Foo {}
struct Bar {
	f &Foo = &Foo(0)
}
fn main() {
	b := &Bar{
		f: &&Foo(1)
	}
}
```

**Comment by spytheman** [comment]
Yeah, one common thing between all these, is that they happen inside &Struct{ } . I am not sure for the exact cause yet, but probably something to do with 
vlib/v/parser/pratt.v prefix_expr method. It does:
`p.is_amp = true`
...
` right = p.expr(token.Precedence.prefix)`
...
`p.is_amp = false`

**Comment by UweKrueger** [comment]
The issue might be fixed by [PR #5133](https://github.com/vlang/v/pull/5133).

**Comment by spytheman** [comment]
The second case indeed was fixed by it.
The third should be by bb9d268b.
@duarteroso can you check if it works for all cases with latest V?

**Comment by duarteroso** [comment]
@spytheman 
All three cases seem to be solved in 0.1.27 bb9d268
Good work guys :+1:

**Comment by duarteroso** [comment]
Sorry guys, found another case where the double ref is added

```
module main

struct Foo {}

pub fn create_instance() &Foo {
	instance := &Foo(0)
	return instance
}
```
