### ISSUE TITLE
a bug in function return value with option

### ISSUE THREAD

**Issue by lydiandy** [vlang/v#5157]
**V version:** 
latest:V 0.1.27 f1f6fb1
**OS:** 
macos
**What did you do?**
here is the example code:
```
module main

fn main() {
	exec('abc') or {
		panic('error is :$err')
	}
}

fn exec(stmt string) ? { //exec function do not need to return,but may need to retrun error
	if stmt == '' {
		return error('stmt is null')
	}
	println(stmt)
}
```

**What did you expect to see?**
just print abc
no panic
 
**What did you see instead?**
abc
V panic: error is :
0   main                                0x0000000109940c60 main + 144
1   main                                0x000000010992b3b4 start + 52

**Comment by yuyi98** [comment]
fixed

**Comment by lydiandy** [comment]
@yuyi98 thanks for fix this issue
I update to  V 0.1.28 9a713ff, and os is macos
and run the example code,It still throw a panic:
'''
abc
V panic: error is :
0   main                                0x000000010424eafa main + 154
1   main                                0x0000000104238bf4 start + 52
2   ???                                 0x0000000000000001 0x0 + 1
Terminated by signal 11 (SIGSEGV)
'''

**Comment by yuyi98** [comment]
Please try this:
```v
module main

fn main() {
	exec('abc') or {
		panic('error is :$err')
	}
}

fn exec(stmt string) ? { //exec function do not need to return,but may need to retrun error
	if stmt == '' {
		return error('stmt is null')
	}
	println(stmt)
	return
}
```

**Comment by lydiandy** [comment]
@yuyi98 

> Please try this:
> 
> ```v
> module main
> 
> fn main() {
> 	exec('abc') or {
> 		panic('error is :$err')
> 	}
> }
> 
> fn exec(stmt string) ? { //exec function do not need to return,but may need to retrun error
> 	if stmt == '' {
> 		return error('stmt is null')
> 	}
> 	println(stmt)
> 	return
> }
> ```

it is right,thank you

**Comment by lydiandy** [comment]
@yuyi98 are you in discord? I can't find your discord account, can you add me?

**Comment by medvednikov** [comment]
He's not unfortunately, blocked in China.
