### ISSUE TITLE
 `arr[i] *= 2` can't compiled

### ISSUE THREAD

**Issue by yar999** [vlang/v#549]
**V version:**  V 0.1.1
**OS:**  windows 10 wsl ubuntu 18.04
**C compiler version:** gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**`arr[i] *= 2` can't compiled**

https://vlang.io/docs#recvs Pure functions 

```
fn multiply_by_2(arr mut []int) {
    for i :=0; i< arr.len; i++ {
        arr[i] *= 2
    }
}

fn main() {
    mut nums := [1, 2, 3]
    multiply_by_2(mut nums)
    println(nums)
}
```

v run f.v got error:

```
root@u18 yst 
> v run f.v
/root//.vlang//f.c: In function ‘multiply_by_2’:
/root//.vlang//f.c:3766:14: error: expected expression before ‘*=’ token
 int tmp2 =   *=  2;
              ^~
V panic: clang error
```

**What did you expect to see?**

Is this a bug?This should compile properly.

**Comment by Henrixounez** [comment]
Actually, the problem is with every operator : 
```
+=
-=
*=
/=
%=
```

**Comment by AurelienFT** [comment]
Fixed https://github.com/vlang/v/pull/579

**Comment by yar999** [comment]
Compilation still failed

```
λ v main.v
/root//.vlang//main.c: In function ‘multiply_by_2’:
/root//.vlang//main.c:3766:35: error: incompatible type for argument 1 of ‘array__get’
 int tmp4 =  ( *(int*) array__get( arr , i) ) + 2;
                                   ^~~
/root//.vlang//main.c:395:8: note: expected ‘array {aka struct array}’ but argument is of type ‘array_int * {aka struct array *}’
  void* array__get(array a, int i) {
        ^~~~~~~~~~
V panic: clang error
```

**V version**:  V 0.1.2
**OS**: windows 10 wsl ubuntu 18.04
**C compiler version**: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by Henrixounez** [comment]
Please share your code @yar999

**Comment by yar999** [comment]
```
fn multiply_by_2(arr mut []int) {
    for i :=0; i< arr.len; i++ {
        arr[i] *= 2
    }
}

fn main() {
    mut nums := [1, 2, 3]
    multiply_by_2(mut nums)
    println(nums)
}
```

**Comment by Smartyue** [comment]
> **V version**: V 0.1.3
> **OS**: windows 10 wsl ubuntu 18.04
> **C compiler version**: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
> 
> ```
> fn multiply_by_2(arr mut []int) {
>     for i :=0; i< arr.len; i++ {
>         arr[i] *= 2
>     }
> }
> 
> fn main() {
>     mut nums := [1, 2, 3]
>     multiply_by_2(mut nums)
>     println(nums)
> }
> ```
> 
> error:
> 
> ```
> /root//.vlang//main.c: In function ‘multiply_by_2’:
> /root//.vlang//main.c:3579:35: error: incompatible type for argument 1 of ‘array__get’
>  int tmp4 =  ( *(int*) array__get( arr , i) ) * 2;
>                                    ^~~
> /root//.vlang//main.c:376:8: note: expected ‘array {aka struct array}’ but argument is of type ‘array_int * {aka struct array *}’
>   void* array__get(array a, int i) {
>         ^~~~~~~~~~
> V panic: clang error
> ```

```rust
fn mulb(arr []int){
  for i:=0;i<arr.len;i++{
     arr[i]=arr[i]*2
  }
}

fn main(){
   nums:=[1,2,3]
   mulb(nums)
   println(nums) // [2, 4, 6]
}
```

**Comment by yar999** [comment]
Nums should be declared mutable ?  @Smartyue

**Comment by Smartyue** [comment]
Please update version to 0.1.3


发自我的iPhone

------------------ Original ------------------

**Comment by yar999** [comment]
是0.1.3的, 按照网站上文档说的,应该不是需要mut的才能修改吗?

**Comment by Smartyue** [comment]
是的，但是我发那个代码的时候用的是0.1.1版本


发自我的iPhone

------------------ Original ------------------

**Comment by yar999** [comment]
估计还不是很完善, 持续关注中.. 谢谢

**Comment by gaoxinge** [comment]
revert these codes 

https://github.com/vlang/v/blob/2a3cf0bec94b1312ac2ffdaa2ca4090a34c8b450/compiler/fn.v#L611-L614

into

```
if is_mut {
    !typ2.starts_with('array_') {
          typ2 += '*'
    }
}
```

can make the code work around

```
fn multiply_by_2(arr mut []int) {
    for i := 0; i < arr.len; i++ {
        arr[i] *= 2
    }
}

fn main() {
    mut nums := [1, 2, 3]
    multiply_by_2(mut nums)
    println(nums)
}
```

**Comment by yar999** [comment]
按照你说的修改之后,重新编译v,就可以编译上面的代码了. 谢谢 @gaoxinge

**Comment by gaoxinge** [comment]
The code below can work

```
fn mulb(arr []int){
  for i:=0;i<arr.len;i++{
     arr[i]=arr[i]*2
  }
}

fn main(){
   nums:=[1,2,3]
   mulb(nums)
   println(nums) // [2, 4, 6]
}
```

because `arr` is an argument, code below will pass regardless of whether `arr` is immutable.

https://github.com/vlang/v/blob/2a3cf0bec94b1312ac2ffdaa2ca4090a34c8b450/compiler/parser.v#L1015-L1017

Further more, if you add `println(v.is_mut)` in the front of these codes:

```
println(v.name)  // array
println(v.type)  // array_int
println(v.is_mut)  // false
if !v.is_mut && !v.is_arg && !p.translated {
    p.error('`$v.name` is immutable')
}
```

you will find that whatever whether you add `mut` keyword on `nums`, these `v.is_mut` is always `false`. It seems that func will not pass `mut` attribute from outside to inside.

**Comment by gaoxinge** [comment]
I think these issue should be reopen. @yar999 @Smartyue @Henrixounez @AurelienFT

**Comment by yar999** [comment]
I'd like to reopen this issue,but I don't know how to reopen it.I shouldn't have permission.

**Comment by yar999** [comment]
I submitted a new issue
https://github.com/vlang/v/issues/581

**Comment by Henrixounez** [comment]
The problem here is not with the Assignement Operators
It doesnt works whether it is `arr[i] *= 2` or `arr[i] = arr[i] * 2`
Thank you for creating a new issue @yar999 .

**Comment by gaoxinge** [comment]
@yar999 @Henrixounez Oh, yes, it is a new issue. And this code 

```
fn mulb(arr []int){
  for i:=0;i<arr.len;i++{
     arr[i]=arr[i]*2
  }
}

fn main(){
   nums:=[1,2,3]
   mulb(nums)
   println(nums) // [2, 4, 6]
}
```

that the `mut` attribute of `nums` isn't passed to the argument `arr` of function `mulb`  should also be discussed.

**Comment by yar999** [comment]
Passing mutable variable to functions issue https://github.com/vlang/v/issues/652 @gaoxinge

**Comment by gaoxinge** [comment]
@yar999 Nice! Thanks!

**Comment by han2015** [comment]
> @yar999 @Henrixounez Oh, yes, it is a new issue. And this code
> 
> ```
> fn mulb(arr []int){
>   for i:=0;i<arr.len;i++{
>      arr[i]=arr[i]*2
>   }
> }
> 
> fn main(){
>    nums:=[1,2,3]
>    mulb(nums)
>    println(nums) // [2, 4, 6]
> }
> ```
> 
> that the `mut` attribute of `nums` isn't passed to the argument `arr` of function `mulb` should also be discussed.

HI @gaoxinge , Don't you think it’s conflict with the rule of `mut`？The nums is immutable, but been changed by `mulb`...

**Comment by gaoxinge** [comment]
@han2015 Oh yes, I open an issue https://github.com/vlang/v/issues/693.
