### ISSUE TITLE
Multi-word usernames break V's compiler on Windows 10.

### ISSUE THREAD

**Issue by KaiTheCEO** [vlang/v#8524]
**V version v0.2:** 
**OS: Microsoft Windows** 

**What did you do?** I installed V on my computer and tried to run it in CMD and Powershell. I have a multi-word username for my PC ("Kai Lyons") and V's compiler DOES NOT WORK with that username.
![image](https://user-images.githubusercontent.com/62919224/106655712-f4960f80-6556-11eb-8a67-c892a8ab74af.png)
This should be an easy fix. Just change the directory into a string, i.e. like me going into the documents folder.
![image](https://user-images.githubusercontent.com/62919224/106655843-20b19080-6557-11eb-8e03-7b733d2068a4.png)

**What did you expect to see?**
I expected to see the V REPL when running "v" by itself.
 
**What did you see instead?**
![image](https://user-images.githubusercontent.com/62919224/106655712-f4960f80-6556-11eb-8a67-c892a8ab74af.png)

**Comment by yuyi98** [comment]
This has been fixed, maybe the installation package has not been updated, can you use `git clone` to try?

**Comment by KaiTheCEO** [comment]
I will test it, this was from the Zip file on the website.

**Comment by KaiTheCEO** [comment]
I just finished, still doesn't work in CMD itself... but for some unknown reason, it works in a VSCode CMD terminal. Oh well, I will consider this something I messed up.

**Comment by KaiTheCEO** [comment]
I did some further testing, it does not work outside of the directory I gitcloned V in.
