### ISSUE TITLE
v: map with enum keys

### ISSUE THREAD

**Issue by nyx-litenite** [vlang/v#8596]
```bash
OS: linux, "Fedora release 33 (Thirty Three)"
Processor: 8 cpus, 64bit, little endian, AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
CC version: cc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)

getwd: /home/litenite/Documents
vmodules: /home/litenite/.vmodules
vroot: /home/litenite/Documents/v
vexe: /home/litenite/Documents/v/v
vexe mtime: 2021-02-06 02:22:44
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.2 57258c2.e83c39c

Git version: git version 2.29.2
Git vroot status: weekly.2021.5-105-ge83c39c8
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 7543de81
```
**What did you do?**
Tried to define a const map of enum keys and string array values
```v
enum TestEnum {
    a b
}
// Notes strings are used for example, since error occurs due to enum key and not values.
const (
    x = {
        .a : 'Alpha'
        .b : 'Beta'
    }
)

println(x[.a])
println(x[.b])
```
**What did you expect to see?**
```bash
Alpha
Beta
```
 
**What did you see instead?**
```bash
test.v:16:3: error: unexpected ``, expecting struct key
   14 |     beta = 'b'
   15 |     x = {
   16 |         .a : 'Alpha'
      |         ^
   17 |         .b : 'Beta'
   18 |     }
```

**Comment by nyx-litenite** [comment]
Related Attempts and Issues
```v
enum TestEnum {
	a b
}

const (
	x = {
		TestEnum.a : 'Alpha'
		TestEnum.b : 'Beta'
	}
)

println(x[TestEnum.a])
println(x[TestEnum.b])

```
gives
```bash
test.v:14:11: error: unexpected ., expecting `:`
   12 | const (
   13 |     x = {
   14 |         TestEnum.a : 'Alpha'
      |                 ^
   15 |         TestEnum.b : 'Beta'
   16 |     }
```



```v
const (
	alpha = 'a'
	beta = 'b'
	x = {
		alpha : 'Alpha'
		beta : 'Beta'
	}
)

println(x[alpha])
println(x[beta])
```
gives 
```bash
test.v:16:3: error: unexpected short struct syntax
   14 |     beta = 'b'
   15 |     x = {
   16 |         alpha : 'Alpha'
      |         ~~~~~~~~~~~~~~~
   17 |         beta : 'Beta'
   18 |     }
test.v:17:3: error: unknown field `beta` in struct literal of type `string`
   15 |     x = {
   16 |         alpha : 'Alpha'
   17 |         beta : 'Beta'
      |         ~~~~~~~~~~~~~
   18 |     }
   19 | )
```
```v
enum TestEnum {
	a b
}

fn enum_to_str(e TestEnum) string {
	return match e {
		.a {'a'}
		.b {'b'}
	}
}

const (
	x = {
		enum_to_str(.a) : 'Alpha'
		enum_to_str(.b) : 'Beta'
	}
)

println(x[enum_to_str(.a)])
println(x[enum_to_str(.a)])

```
gives
```bash
test.v:14:14: error: unexpected (, expecting `:`
   12 | const (
   13 |     x = {
   14 |         enum_to_str(.a) : 'Alpha'
      |                    ^
   15 |         enum_to_str(.b) : 'Beta'
   16 |     }
```

**Comment by ntrel** [comment]
Generally these are all caused by the map literal syntax only supporting string or integer literals as keys. That is solved by changing the syntax in https://github.com/vlang/v/pull/8608.

```v
    x = {
        .a : 'Alpha'
        .b : 'Beta'
    }
```
The above is wrong, V can't know what `.a` is.

```
test.v:14:11: error: unexpected ., expecting `:`
   12 | const (
   13 |     x = {
   14 |         TestEnum.a : 'Alpha'
      |                 ^
```
I've improved the error message in https://github.com/vlang/v/pull/8610 so you'll see:
```
mapenum2.v:7:11: error: unexpected `.`, expecting `:` after struct field name
```

**Comment by nyx-litenite** [comment]
Then this needs to be re-worded from the documentation :/ 
```v
// NB: map keys can have any type, `int` in this case,
// and the whole map can be initialized using this short syntax:
numbers := {
	1: 'one'
	2: 'two'
}
println(numbers)
```

Note that it says ANY type and that int was just used in that case. 

**Alex M also [said](https://discord.com/channels/592103645835821068/592294828432424960/807433458082644028) that enums should work, so I don't think your PR is a correct course of action.**

**Comment by nyx-litenite** [comment]
The docs clearly say that map keys can be of any type
```v
// NB: map keys can have any type, `int` in this case,
// and the whole map can be initialized using this short syntax:
numbers := {
	1: 'one'
	2: 'two'
}
println(numbers)
```
and Alex M said that 
```v
x = {
  TestEnum.a : ...
  ```
 [should definitely work](https://discord.com/channels/592103645835821068/592294828432424960/807433458082644028), so making it a parsing error would be incorrect.

**Comment by ntrel** [comment]
```v
const (
	alpha = 'a'
	beta = 'b'
	x = {
		alpha : 'Alpha'
		beta : 'Beta'
	}
)
```
This is fixed by #8608. I've renamed this issue as the remaining problem is to support an enum key type for map keys.

**Comment by ntrel** [comment]
```v
const (
	x = {
		enum_to_str(.a) : 'Alpha'
		enum_to_str(.b) : 'Beta'
	}
)
```
This is also supported by the new syntax, if you use the `TestEnum` prefix. I added a version of this as a test to the same pull.

**Comment by nyx-litenite** [comment]
@serkonda7 I'm on commit 114c382 (most recent as of posting this) and still get a compilation error
when I try my first example in the comments.

**Comment by serkonda7** [comment]
@nyx-litenite have you used the `map` keyword?

**Comment by nyx-litenite** [comment]
Ah no, I missed that in your example. I'm at work currently, so if it compiles for you then I'm good to close this 👍

**Comment by serkonda7** [comment]
Let's keep it open a little longer, I want to try, of I can improve the heuristic that differentiates between structs and maps.

**Comment by danieldaeschle** [comment]
```
main/main.v:7:17: error: unexpected token `.`, expecting `:` after struct field name
    5 | const (
    6 |     x = {
    7 |         TestEnum.a: 'Alpha'
      |                 ^
    8 |         TestEnum.b: 'Beta'
    9 |     }
```

**Comment by yuyi98** [comment]
Fixed.
```v
enum TestEnum {
    a b
}
// Notes strings are used for example, since error occurs due to enum key and not values.
const (
    x = {
        TestEnum.a : 'Alpha'
        TestEnum.b : 'Beta'
    }
)

fn main() {
	println(x[.a])
	println(x[.b])
}

PS D:\Test\v\tt1> v run .
Alpha
Beta
```
