### ISSUE TITLE
Alias not handled as underlying type

### ISSUE THREAD

**Issue by duarteroso** [vlang/v#9683]
**V version:** 0.2.2
**OS:** Linux

**What did you do?**
```v
module main

type ALchar = char

fn main() {
	c1 := &char(0)
	c2 := &ALchar(0)
	println(c1)
	println(c2)
}
```

**What did you expect to see?**
Concrete type and alias type to show the same behaviour.
 
**What did you see instead?**
Type alias is handled differently from underlying type.

```v
./main.v:7:9: error: cannot convert type `int literal` to `ALchar` (alias to `char`)
    5 | fn main() {
    6 |     c1 := &char(0)
    7 |     c2 := &ALchar(0)
      |            ~~~~~~~~~
    8 |     println(c1)
    9 |     println(c2)
```

**Comment by medvednikov** [comment]
Fixed.

**Comment by duarteroso** [comment]
Sorry Alex, will have to reopen this as it is not fixed.

```v
module main

type CEnum = int

enum Enum {
	value = 1
}

fn foo(n int) {
	println(n)
}

fn main() {
	e := Enum.value
	foo(CEnum(e)) // error: cannot convert type `Enum` to `CEnum` (alias to `int`)
	foo(int(e)) // 1
}
```
`error: cannot convert type Enum to CEnum (alias to int)`

Perhaps I should open a new ticket?

**Comment by duarteroso** [comment]
Also, running the first example doesn't give the exact values. Should both print exactly the same?
```v
module main

type ALchar = char

fn main() {
	c1 := &char(0)
	c2 := &ALchar(0)
	println(c1) // &0
	println(c2) // 7ffe5830bc80
}
```

**Comment by danieldaeschle** [comment]
Create two new issues please
